### ISSUE TITLE
code for box plots

### ISSUE THREAD

**Issue by bigfishfour** [DeepMed-Lab-ECNU/MagicNet#11]
Hello author, thank you for doing such an excellent job! Sorry to bother you, may I ask how your box plots diagram was drawn, what parameters did you input, and do you have specific code?

**Comment by DuowenC** [comment]
Sorry for my late reply and out boxplot is ploted by MatLab and the inputs include the final metrics for all cases (e.g., dice, NSD, ...), you can try this in MatLab!!!
