### ISSUE TITLE
How to replicate the result of other methods in table 1

### ISSUE THREAD

**Issue by feiyu12138** [DeepMed-Lab-ECNU/MagicNet#2]
Hi!

Congrats on this nice work! This semi-supervised method is amazing. In the meanwhile, it's a little hard for me replicate the performance of other methods in the table 1 such as ICT or CPS. Would you mind release the code concerning these approaches? 

Thank you!

**Comment by DuowenC** [comment]
Hi!

Thank you for your attention to our work! The implementation codes for the other methods in Table 1 are still being organized and will require some time. Alternatively, you can refer to the implementation of these methods in SSL4MIS. I hope my response can be helpful to you.

**Comment by RY-97** [comment]
> Hi!
> 
> Thank you for your attention to our work! The implementation codes for the other methods in Table 1 are still being organized and will require some time. Alternatively, you can refer to the implementation of these methods in SSL4MIS. I hope my response can be helpful to you.

Hello, thumbs up for your work and appreciate it. Here, I want to find the code of the comparative experimental method in Table 1. Can you contribute a copy? Grateful.
