### ISSUE TITLE
About training with my own dataset

### ISSUE THREAD

**Issue by Y01011001** [DeepMed-Lab-ECNU/MagicNet#3]
Hi！This semi-supervised method is truly amazing！

I just started learning semi-supervised learning，I had some difficulty trying to train on my own dataset.
What is the label of  the unlabelled data in h5？And when I train with one label, I can train with the labelled data, but always appears "IndexError: Target ... is out of bounds." when joining unlabeled data. Is there anything I should change, please.

Thank you! : )

**Comment by DuowenC** [comment]
Hi, thanks for your attention to our work! 

The label of unlabelled data is the Ground-Truth(GT) in the .h5 format, which is the same as labeled data. But these labels will not be used in the SSL training. In fact, we follow the formulation of previous SSL methods like UA-MT, SSL4MIS. These methods all choose part of dataset as labeled data, and the remaining as unlabeled data. These datasets are de facto fully-labeled datasets. I hope my response can help you!
