### ISSUE TITLE
BTCV esophagus

### ISSUE THREAD

**Issue by Rainw00d** [DeepMed-Lab-ECNU/MagicNet#8]
您好，我跑出 30% labeled BTCV数据集的结果中，esophagus 各项的metric都是零

**Comment by RY-97** [comment]
![image](https://github.com/DeepMed-Lab-ECNU/MagicNet/assets/88662555/ad092d1b-d6b6-4743-a9a9-e9c40746f06e)
ni'y你有解决这个问题吗？我已经torch版本降了还是没解决

**Comment by DuowenC** [comment]
@Rainw00d We released our checkpoint and training logs on for [model_checkpoint](https://github.com/DeepMed-Lab-ECNU/MagicNet/releases) 30% and 40% BTCV setting, hope these can help you!

**Comment by DuowenC** [comment]
> ![image](https://private-user-images.githubusercontent.com/88662555/318356510-ad092d1b-d6b6-4743-a9a9-e9c40746f06e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NjU5NDUsIm5iZiI6MTczMDg2NTY0NSwicGF0aCI6Ii84ODY2MjU1NS8zMTgzNTY1MTAtYWQwOTJkMWItZDZiNi00NzQzLWE5YTktZTljNDA3NDZmMDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA0MDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjOGQwMDEwMDVjOTYyZjJkZDZlNTU3M2ZhZTMzMmRjZmI1NWMyZDg4M2M3ZWY2MDhmNDdlODBlM2ZjNmVhNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CgMukoPqfVha-wohCCXd4xKvBowcq3JXA0NyaYfeNFw) ni'y你有解决这个问题吗？我已经torch版本降了还是没解决

@RY-97 这个问题是多卡训练导致的报错。目前我们的codebase是基于单卡的，暂不支持多卡，多卡可能需要从数据读入和模型修改成多卡形式。
