### ISSUE TITLE
Don't understand the location reasoning part.

### ISSUE THREAD

**Issue by GYDDHPY** [DeepMed-Lab-ECNU/MagicNet#9]
Thank you for your great job.

I have difficulty in learning the location reasoning part. 
The paper assigns a location value relative to the patch for each cube. For the patch-based training method, the same cube may occur in different patch due to the random crop method. Thus the same cube area may be assigned different location value. 
However, the location reasoning procedure seems just rely on the feature from the cube itself but doens't consider the relationship between cubes from the same patch. I cannot understand that how the network be able to predict the different location value when the cube feature is always the same.

Looking forward to you reply.

Best wishes.

**Comment by DuowenC** [comment]
Our cube locationing part relies on the relative location for one cropped volume, not representing absolute location. For deeper interpretation, you can refer to previous work "Domain adaptive relational
reasoning for 3d multi-organ segmentation" in MICCAI 2020.
